package BoardModules;

/**
* BoardModules/BoardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class BoardHolder implements org.omg.CORBA.portable.Streamable
{
  public BoardModules.Board value = null;

  public BoardHolder ()
  {
  }

  public BoardHolder (BoardModules.Board initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoardModules.BoardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoardModules.BoardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoardModules.BoardHelper.type ();
  }

}
