package BoardModules;


/**
* BoardModules/Board.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class Board implements org.omg.CORBA.portable.IDLEntity
{
  public String groupname = null;

  public Board ()
  {
  } // ctor

  public Board (String _groupname)
  {
    groupname = _groupname;
  } // ctor

} // class Board
