package BoardModules;


/**
* BoardModules/DestinationUnreachable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public final class DestinationUnreachable extends org.omg.CORBA.UserException
{
  public String unreachableBoard = null;

  public DestinationUnreachable ()
  {
    super(DestinationUnreachableHelper.id());
  } // ctor

  public DestinationUnreachable (String _unreachableBoard)
  {
    super(DestinationUnreachableHelper.id());
    unreachableBoard = _unreachableBoard;
  } // ctor


  public DestinationUnreachable (String $reason, String _unreachableBoard)
  {
    super(DestinationUnreachableHelper.id() + "  " + $reason);
    unreachableBoard = _unreachableBoard;
  } // ctor

} // class DestinationUnreachable
