package BoardModules;

import java.util.Objects;


/**
* BoardModules/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public String content = null;
  public String author = null;
  public String timestamp = null;

  public Message ()
  {
  } // ctor

  public Message (String _content, String _author, String _timestamp)
  {
    content = _content;
    author = _author;
    timestamp = _timestamp;
  } // ctor

    @Override
    public String toString() {
        return timestamp + " " + author + ": " + content;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + Objects.hashCode(this.content);
        hash = 37 * hash + Objects.hashCode(this.author);
        hash = 37 * hash + Objects.hashCode(this.timestamp);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Message other = (Message) obj;
        if (!Objects.equals(this.content, other.content)) {
            return false;
        }
        if (!Objects.equals(this.author, other.author)) {
            return false;
        }
        if (!Objects.equals(this.timestamp, other.timestamp)) {
            return false;
        }
        return true;
    }
    
    
} // class Message
