package BoardModules;


/**
* BoardModules/MessageListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 12. Januar 2016 10:29 Uhr MEZ
*/

abstract public class MessageListHelper
{
  private static String  _id = "IDL:BoardModules/MessageList:1.0";

  public static void insert (org.omg.CORBA.Any a, BoardModules.Message[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BoardModules.Message[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = BoardModules.MessageHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (BoardModules.MessageListHelper.id (), "MessageList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BoardModules.Message[] read (org.omg.CORBA.portable.InputStream istream)
  {
    BoardModules.Message value[] = null;
    int _len0 = istream.read_long ();
    value = new BoardModules.Message[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = BoardModules.MessageHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BoardModules.Message[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      BoardModules.MessageHelper.write (ostream, value[_i0]);
  }

}
