package BoardModules;


/**
* BoardModules/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public String content = null;
  public String author = null;
  public String timestamp = null;

  public Message ()
  {
  } // ctor

  public Message (String _content, String _author, String _timestamp)
  {
    content = _content;
    author = _author;
    timestamp = _timestamp;
  } // ctor

    @Override
    public String toString() {
        return timestamp + " " + author + ": " + content;
    }
  
  

} // class Message
