package BoardModules;


/**
* BoardModules/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public String content = null;
  public String author = null;
  public String timestamp = null;

  public Message ()
  {
  } // ctor

  public Message (String _content, String _author, String _timestamp)
  {
    content = _content;
    author = _author;
    timestamp = _timestamp;
  } // ctor

} // class Message
