package BoardModules;


/**
* BoardModules/MessageListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public final class MessageListHolder implements org.omg.CORBA.portable.Streamable
{
  public BoardModules.Message value[] = null;

  public MessageListHolder ()
  {
  }

  public MessageListHolder (BoardModules.Message[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoardModules.MessageListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoardModules.MessageListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoardModules.MessageListHelper.type ();
  }

}
