package BoardModules;

/**
* BoardModules/UnknownUserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class UnknownUserHolder implements org.omg.CORBA.portable.Streamable
{
  public BoardModules.UnknownUser value = null;

  public UnknownUserHolder ()
  {
  }

  public UnknownUserHolder (BoardModules.UnknownUser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoardModules.UnknownUserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoardModules.UnknownUserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoardModules.UnknownUserHelper.type ();
  }

}
