package BoardModules;


/**
* BoardModules/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  public User ()
  {
  } // ctor

  public User (String _name)
  {
    name = _name;
  } // ctor

} // class User
