package BoardModules;


/**
* BoardModules/UserListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 12. Januar 2016 10:29 Uhr MEZ
*/

public final class UserListHolder implements org.omg.CORBA.portable.Streamable
{
  public BoardModules.User value[] = null;

  public UserListHolder ()
  {
  }

  public UserListHolder (BoardModules.User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoardModules.UserListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoardModules.UserListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoardModules.UserListHelper.type ();
  }

}
