package BoardModules;


/**
* BoardModules/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  public User ()
  {
  } // ctor

  public User (String _name)
  {
    name = _name;
  } // ctor

} // class User
