package BoardModules;


/**
* BoardModules/VirtualGroup.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class VirtualGroup implements org.omg.CORBA.portable.IDLEntity
{
  public String vgoupname = null;
  public BoardModules.Board members[] = null;

  public VirtualGroup ()
  {
  } // ctor

  public VirtualGroup (String _vgoupname, BoardModules.Board[] _members)
  {
    vgoupname = _vgoupname;
    members = _members;
  } // ctor

} // class VirtualGroup
