package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/_BoardServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idls/BoardModules.idl
* Donnerstag, 14. Januar 2016 14:02 Uhr MEZ
*/

public class _BoardServiceStub extends org.omg.CORBA.portable.ObjectImpl implements BoardModules.BasicServices.BoardService
{

  public void sendMessage (BoardModules.User user, BoardModules.Message message, String source) throws BoardModules.UnknownUser
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendMessage", true);
                BoardModules.UserHelper.write ($out, user);
                BoardModules.MessageHelper.write ($out, message);
                $out.write_string (source);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BoardModules/UnknownUser:1.0"))
                    throw BoardModules.UnknownUserHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sendMessage (user, message, source        );
            } finally {
                _releaseReply ($in);
            }
  } // sendMessage

  public void checkUser (BoardModules.User user) throws BoardModules.UnknownUser
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("checkUser", true);
                BoardModules.UserHelper.write ($out, user);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BoardModules/UnknownUser:1.0"))
                    throw BoardModules.UnknownUserHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                checkUser (user        );
            } finally {
                _releaseReply ($in);
            }
  } // checkUser

  public void removeMessage (BoardModules.User user, BoardModules.Message message, String source) throws BoardModules.UnknownUser
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removeMessage", true);
                BoardModules.UserHelper.write ($out, user);
                BoardModules.MessageHelper.write ($out, message);
                $out.write_string (source);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:BoardModules/UnknownUser:1.0"))
                    throw BoardModules.UnknownUserHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removeMessage (user, message, source        );
            } finally {
                _releaseReply ($in);
            }
  } // removeMessage

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoardModules/BasicServices/BoardService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _BoardServiceStub
