package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/AdministrationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public interface AdministrationServiceOperations 
{
  void createVirtualGroup (String vgroupname);
  void loginToVirtualGroup (String vgroupname);
  String[] getAllVirtualGroups ();
  void forwardMessageToBoards (String[] boards, BoardModules.Message message) throws BoardModules.DestinationUnreachable;
  void createUser (BoardModules.User newuser);
} // interface AdministrationServiceOperations
