package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/AdministrationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public interface AdministrationServiceOperations 
{
  void createVirtualGroup (String vgroupname);
  void loginToVirtualGroup (String vgroupname);
  String[] getAllVirtualGroups ();
  void forwardMessageToBoards (String[] boards, BoardModules.Message message) throws BoardModules.DestinationUnreachable;
  void createUser (BoardModules.User newuser);
} // interface AdministrationServiceOperations
