package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/AdministrationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public interface AdministrationService extends AdministrationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdministrationService
