package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/BoardService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public interface BoardService extends BoardServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoardService
