package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/BoardServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 12. Januar 2016 10:29 Uhr MEZ
*/

public interface BoardServiceOperations 
{
  void sendMessage (BoardModules.User user, BoardModules.Message message, String destination) throws BoardModules.DestinationUnreachable, BoardModules.UnknownUser;
  void checkUser (BoardModules.User user) throws BoardModules.UnknownUser;
} // interface BoardServiceOperations
