package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/BoardServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 12. Januar 2016 10:29 Uhr MEZ
*/

public abstract class BoardServicePOA extends org.omg.PortableServer.Servant
 implements BoardModules.BasicServices.BoardServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendMessage", new java.lang.Integer (0));
    _methods.put ("checkUser", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BoardModules/BasicServices/BoardService/sendMessage
       {
         try {
           BoardModules.User user = BoardModules.UserHelper.read (in);
           BoardModules.Message message = BoardModules.MessageHelper.read (in);
           String destination = in.read_string ();
           this.sendMessage (user, message, destination);
           out = $rh.createReply();
         } catch (BoardModules.DestinationUnreachable $ex) {
           out = $rh.createExceptionReply ();
           BoardModules.DestinationUnreachableHelper.write (out, $ex);
         } catch (BoardModules.UnknownUser $ex) {
           out = $rh.createExceptionReply ();
           BoardModules.UnknownUserHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // BoardModules/BasicServices/BoardService/checkUser
       {
         try {
           BoardModules.User user = BoardModules.UserHelper.read (in);
           this.checkUser (user);
           out = $rh.createReply();
         } catch (BoardModules.UnknownUser $ex) {
           out = $rh.createExceptionReply ();
           BoardModules.UnknownUserHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoardModules/BasicServices/BoardService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BoardService _this() 
  {
    return BoardServiceHelper.narrow(
    super._this_object());
  }

  public BoardService _this(org.omg.CORBA.ORB orb) 
  {
    return BoardServiceHelper.narrow(
    super._this_object(orb));
  }


} // class BoardServicePOA
