package BoardModules.BasicServices;

/**
* BoardModules/BasicServices/ViewServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class ViewServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public BoardModules.BasicServices.ViewService value = null;

  public ViewServiceHolder ()
  {
  }

  public ViewServiceHolder (BoardModules.BasicServices.ViewService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoardModules.BasicServices.ViewServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoardModules.BasicServices.ViewServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoardModules.BasicServices.ViewServiceHelper.type ();
  }

}
