package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/ViewServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 12. Januar 2016 10:29 Uhr MEZ
*/

public interface ViewServiceOperations 
{
  BoardModules.Message[] getAllMessageByDestination (String destination) throws BoardModules.DestinationUnreachable;
  boolean getState ();
} // interface ViewServiceOperations
