package BoardModules.BasicServices;


/**
* BoardModules/BasicServices/ViewService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Freitag, 15. Januar 2016 20:10 Uhr MEZ
*/

public interface ViewService extends ViewServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ViewService
