package BoardModules.AdvancedServices;


/**
* BoardModules/AdvancedServices/_VirtualGroupServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Mittwoch, 13. Januar 2016 18:19 Uhr MEZ
*/

public class _VirtualGroupServiceStub extends org.omg.CORBA.portable.ObjectImpl implements BoardModules.AdvancedServices.VirtualGroupService
{

  public void addMember (String boardname, BoardModules.User[] users)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addMember", true);
                $out.write_string (boardname);
                BoardModules.UserListHelper.write ($out, users);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addMember (boardname, users        );
            } finally {
                _releaseReply ($in);
            }
  } // addMember

  public void removeMember (String boardname)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removeMember", true);
                $out.write_string (boardname);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removeMember (boardname        );
            } finally {
                _releaseReply ($in);
            }
  } // removeMember

  public void createBackupOfVirtualGroup (BoardModules.StringListHolder membernames, BoardModules.UserListHolder users, BoardModules.MessageListHolder messages)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createBackupOfVirtualGroup", true);
                $in = _invoke ($out);
                membernames.value = BoardModules.StringListHelper.read ($in);
                users.value = BoardModules.UserListHelper.read ($in);
                messages.value = BoardModules.MessageListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                createBackupOfVirtualGroup (membernames, users, messages        );
            } finally {
                _releaseReply ($in);
            }
  } // createBackupOfVirtualGroup

  public void heartbeat ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("heartbeat", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                heartbeat (        );
            } finally {
                _releaseReply ($in);
            }
  } // heartbeat

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoardModules/AdvancedServices/VirtualGroupService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _VirtualGroupServiceStub
