package BoardModules.AdvancedServices;

/**
* BoardModules/AdvancedServices/VirtualGroupServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Mittwoch, 13. Januar 2016 18:19 Uhr MEZ
*/

public final class VirtualGroupServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public BoardModules.AdvancedServices.VirtualGroupService value = null;

  public VirtualGroupServiceHolder ()
  {
  }

  public VirtualGroupServiceHolder (BoardModules.AdvancedServices.VirtualGroupService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoardModules.AdvancedServices.VirtualGroupServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoardModules.AdvancedServices.VirtualGroupServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoardModules.AdvancedServices.VirtualGroupServiceHelper.type ();
  }

}
