package BoardModules.AdvancedServices;


/**
* BoardModules/AdvancedServices/VirtualBoardService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public interface VirtualBoardService extends VirtualBoardServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface VirtualBoardService
