package BoardModules.AdvancedServices;


/**
* BoardModules/AdvancedServices/VirtualGroupServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 12. Januar 2016 10:29 Uhr MEZ
*/

abstract public class VirtualGroupServiceHelper
{
  private static String  _id = "IDL:BoardModules/AdvancedServices/VirtualGroupService:1.0";

  public static void insert (org.omg.CORBA.Any a, BoardModules.AdvancedServices.VirtualGroupService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BoardModules.AdvancedServices.VirtualGroupService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BoardModules.AdvancedServices.VirtualGroupServiceHelper.id (), "VirtualGroupService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BoardModules.AdvancedServices.VirtualGroupService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_VirtualGroupServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BoardModules.AdvancedServices.VirtualGroupService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BoardModules.AdvancedServices.VirtualGroupService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BoardModules.AdvancedServices.VirtualGroupService)
      return (BoardModules.AdvancedServices.VirtualGroupService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BoardModules.AdvancedServices._VirtualGroupServiceStub stub = new BoardModules.AdvancedServices._VirtualGroupServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BoardModules.AdvancedServices.VirtualGroupService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BoardModules.AdvancedServices.VirtualGroupService)
      return (BoardModules.AdvancedServices.VirtualGroupService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BoardModules.AdvancedServices._VirtualGroupServiceStub stub = new BoardModules.AdvancedServices._VirtualGroupServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
