package BoardModules.AdvancedServices;

/**
* BoardModules/AdvancedServices/VirtualBoardServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public final class VirtualBoardServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public BoardModules.AdvancedServices.VirtualBoardService value = null;

  public VirtualBoardServiceHolder ()
  {
  }

  public VirtualBoardServiceHolder (BoardModules.AdvancedServices.VirtualBoardService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoardModules.AdvancedServices.VirtualBoardServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoardModules.AdvancedServices.VirtualBoardServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoardModules.AdvancedServices.VirtualBoardServiceHelper.type ();
  }

}
