package BoardModules.AdvancedServices;


/**
* BoardModules/AdvancedServices/VirtualBoardServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public abstract class VirtualBoardServicePOA extends org.omg.PortableServer.Servant
 implements BoardModules.AdvancedServices.VirtualBoardServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAllMembers", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BoardModules/AdvancedServices/VirtualBoardService/getAllMembers
       {
         String $result[] = null;
         $result = this.getAllMembers ();
         out = $rh.createReply();
         BoardModules.StringListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoardModules/AdvancedServices/VirtualBoardService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public VirtualBoardService _this() 
  {
    return VirtualBoardServiceHelper.narrow(
    super._this_object());
  }

  public VirtualBoardService _this(org.omg.CORBA.ORB orb) 
  {
    return VirtualBoardServiceHelper.narrow(
    super._this_object(orb));
  }


} // class VirtualBoardServicePOA
