package BoardModules.AdvancedServices;


/**
* BoardModules/AdvancedServices/VirtualGroupService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Mittwoch, 13. Januar 2016 18:19 Uhr MEZ
*/

public interface VirtualGroupService extends VirtualGroupServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface VirtualGroupService
