package BoardModules.AdvancedServices;


/**
* BoardModules/AdvancedServices/VirtualGroupServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tobias/Documents/NetBeansProjects/VS2_GitRepository/IDL-Definitions/src/idls/BoardModules.idl
* Donnerstag, 7. Januar 2016 20:23 Uhr MEZ
*/

public interface VirtualGroupServiceOperations 
{
  void addMember (String boardname, BoardModules.User[] users);
  void removeMember (String boardname);
  void createBackupOfVirtualGroup (BoardModules.UserListHolder users, BoardModules.MessageListHolder messages);
} // interface VirtualGroupServiceOperations
