package BoardModules.AdvancedServices;


/**
* BoardModules/AdvancedServices/VirtualBoardServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoardModules.idl
* Dienstag, 15. Dezember 2015 18:00 Uhr MEZ
*/

public interface VirtualBoardServiceOperations 
{
  String[] getAllMembers ();
} // interface VirtualBoardServiceOperations
