
// Version 0.1, von Tobias Mueller, 15.12.2015 - IDL-Definition angelegt
// Version 0.2, von Tobias Mueller, 07.01.2015 - Aenderung bei VirtualBoardService und unbenannt in VirtualGroupService
//                                             - Kleinere Aenderung bei BoardService, ViewService
//                                             - Board und VirtualGroup auskommentiert, UserList eingefügt
module BoardModules {
    
    struct Message {
        string content;
        string author;
        string timestamp;
    };

    struct User {
        string name;
    };

    //! Wird nicht benutzt
    //struct Board {
    //    string groupname;
    //};
    //struct VirtualGroup {
    //    string vgoupname;
    //    sequence<Board> members;
    //};

    exception DestinationUnreachable {
        string unreachableBoard;
    };

    exception UnknownUser {
        string username;
    };

    typedef sequence<string> StringList;
    typedef sequence<Message> MessageList;
    typedef sequence<User> UserList;

    module BasicServices {
        interface AdministrationService {
            void createVirtualGroup(in string vgroupname);
            void loginToVirtualGroup(in string vgroupname);
            StringList getAllVirtualGroups();

            void forwardMessageToBoards(in StringList boards, in Message message) raises (DestinationUnreachable);
            void createUser(in User newuser);
            StringList getAllUsers();

            void removeUser(in User user) raises (UnknownUser);
        };

        interface BoardService {
            void sendMessage(in User user, in Message message, in string source) raises (UnknownUser);
            void checkUser(in User user) raises (UnknownUser);
            void removeMessage(in User user, in Message message, in string source) raises (UnknownUser);
        };

        interface ViewService {
            MessageList getAllMessageByDestination(in string destination) raises (DestinationUnreachable);
            boolean getState();
        };
    };

    module AdvancedServices {
        interface VirtualGroupService {
            void addMember(in string boardname, in UserList users);
            void removeMember(in string boardname);
            void createBackupOfVirtualGroup(out StringList membernames, out UserList users, out MessageList messages);
            void heartbeat();
        };
    };
};
